services:
  app:
    build: .
    container_name: sistema_tramite_app
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - db
    volumes:
      # Volúmenes para persistir archivos subidos
      - tramite_documentos:/var/www/html/controller/tramite/documentos
      - tramite_area_documentos:/var/www/html/controller/tramite_area/documentos
      - persona_fotos:/var/www/html/controller/persona/FOTO
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    restart: always

  db:
    image: mysql:8.0
    container_name: sistema_tramite_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sis_tramite.sql:/docker-entrypoint-initdb.d/sis_tramite.sql
    ports:
      - "${DB_PORT}:3306"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: sistema_tramite_phpmyadmin
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${PHPMYADMIN_PORT}:80"
    depends_on:
      - db
    restart: always

volumes:
  mysql_data:
  tramite_documentos:
  tramite_area_documentos:
  persona_fotos:
